### ISSUE TITLE
So...

### ISSUE THREAD

**Issue by Jet0038** [proxikal/Echo#2]
So echos dead, merged with hexacircle. No reviving it, 100's of servers gone?

Just curious, one of us beta people could run the downgraded echo bot...?

Just an idea, I miss the bot myself and when I can will be selfhosting the old beast.

**Comment by proxikal** [comment]
Actually @Jet0038 Echo is being rewritten as a personal bot AutoGo. It's almost done actually https://autogo.xtclabs.net and has almost all the same functions as Echo. And I'll be revamping the Plugin system as well..be sure to keep updated!

**Comment by Dog2puppy** [comment]
Proxy?!?!?!!!!!!???
