### ISSUE TITLE
self-assign roles based on games played

### ISSUE THREAD

**Issue by Drexl** [proxikal/Echo#3]
I would like any user to be able to self-assign an empty role to indicate which games they play, and query the complete list of game-related roles. How can I accomplish this?

**Comment by proxikal** [comment]
There are a few ways to do something like this. best bet is to create your `gaming roles` from there you need to make a trigger for each gaming role
`.auto &.Overwatch={init}{role:Overwatch}You're now in Overwatch!` 
When someone types `.Overwatch` they will recieve the role Overwatch.

Write down all the gaming roles you have a rule for. and than make a new rule for listing them all.
```
.auto &.list-roles={init}Here's your list {/user}!
.Overwatch - Gives you Overwatch role!
.Anothergame - Add another keyword here!
.AndAnother! And so on...
```

**Comment by Drexl** [comment]
The issue with this solution unfortunately is that I want any  user to be able to create a new empty (no permissions) role. This enables users to add games to the list if it's not present. Once created it would ideally be added to the list automatically.

**Comment by proxikal** [comment]
Ah, for security reasons Echo does not have access to create roles or channels dynamically through his a.r.s (As of now) However, once i revamp the system to my current knowledge level I'm hoping that security issue will be resolved.

**Comment by Drexl** [comment]
Ah ok. I'll use the other solution for now then and anxiously await future development. :)
Thank you for your help! ^_^
