### ISSUE TITLE
Parsing error

### ISSUE THREAD

**Issue by Shiikii** [proxikal/Echo#8]
By accident, during adding ARS trigger({:}*.adres.*), I forgot '&' before '{:}'. Now I can't use .viewauto .delauto .wipeauto, all of these result in 
>error parsing regexp: missing argument to repetition operator: *
>Your regex format needs to be golang found here: https://regex101.com

Trying to delete this trigger, without & result in 
>The trigger: {:}*.adres.* was not found in your default autoresponse file.

How to fix it? ^^;

**Comment by proxikal** [comment]
Use .grabars and manually take the rule out of your json file. Than drag the file back into discord and Echo will let you know if it was installed or not.

**Comment by Shiikii** [comment]
I would never think, such simple trick is available for Echo!

Helped, thanks for your help & hard work on developing Echo!

Thread to close
